### ISSUE TITLE
¿Laboratorio?

### ISSUE THREAD

**Issue by satuelisa** [rolando-ms/Machine-vision#3]
Avísame por favor si vas a llevar a cabo actividades de laboratorio o no. Si lo llevas, tienes un mes para completar todo.

**Comment by rolando-ms** [comment]
No llevo el laboratorio.

**Comment by satuelisa** [comment]
ok

**Comment by satuelisa** [comment]
Quita la carpeta que dice lab, entonces. Es confuso.
